/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnauthSignupRouteImport } from './routes/_unauth/signup'
import { Route as UnauthLoginRouteImport } from './routes/_unauth/login'
import { Route as AuthUserRouteImport } from './routes/_auth/user'
import { Route as AuthAdminRouteImport } from './routes/_auth/admin'
import { Route as AuthUserIndexRouteImport } from './routes/_auth/user/index'
import { Route as AuthAdminIndexRouteImport } from './routes/_auth/admin/index'
import { Route as AuthUserHomeRouteImport } from './routes/_auth/user/home'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthSignupRoute = UnauthSignupRouteImport.update({
  id: '/_unauth/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthLoginRoute = UnauthLoginRouteImport.update({
  id: '/_unauth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUserRoute = AuthUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAdminRoute = AuthAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUserIndexRoute = AuthUserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthUserRoute,
} as any)
const AuthAdminIndexRoute = AuthAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthAdminRoute,
} as any)
const AuthUserHomeRoute = AuthUserHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthUserRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthAdminRouteWithChildren
  '/user': typeof AuthUserRouteWithChildren
  '/login': typeof UnauthLoginRoute
  '/signup': typeof UnauthSignupRoute
  '/user/home': typeof AuthUserHomeRoute
  '/admin/': typeof AuthAdminIndexRoute
  '/user/': typeof AuthUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof UnauthLoginRoute
  '/signup': typeof UnauthSignupRoute
  '/user/home': typeof AuthUserHomeRoute
  '/admin': typeof AuthAdminIndexRoute
  '/user': typeof AuthUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/admin': typeof AuthAdminRouteWithChildren
  '/_auth/user': typeof AuthUserRouteWithChildren
  '/_unauth/login': typeof UnauthLoginRoute
  '/_unauth/signup': typeof UnauthSignupRoute
  '/_auth/user/home': typeof AuthUserHomeRoute
  '/_auth/admin/': typeof AuthAdminIndexRoute
  '/_auth/user/': typeof AuthUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/user'
    | '/login'
    | '/signup'
    | '/user/home'
    | '/admin/'
    | '/user/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/user/home' | '/admin' | '/user'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_auth/admin'
    | '/_auth/user'
    | '/_unauth/login'
    | '/_unauth/signup'
    | '/_auth/user/home'
    | '/_auth/admin/'
    | '/_auth/user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  UnauthLoginRoute: typeof UnauthLoginRoute
  UnauthSignupRoute: typeof UnauthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauth/signup': {
      id: '/_unauth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof UnauthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauth/login': {
      id: '/_unauth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/user': {
      id: '/_auth/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof AuthUserRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/admin': {
      id: '/_auth/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthAdminRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/user/': {
      id: '/_auth/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof AuthUserIndexRouteImport
      parentRoute: typeof AuthUserRoute
    }
    '/_auth/admin/': {
      id: '/_auth/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthAdminIndexRouteImport
      parentRoute: typeof AuthAdminRoute
    }
    '/_auth/user/home': {
      id: '/_auth/user/home'
      path: '/home'
      fullPath: '/user/home'
      preLoaderRoute: typeof AuthUserHomeRouteImport
      parentRoute: typeof AuthUserRoute
    }
  }
}

interface AuthAdminRouteChildren {
  AuthAdminIndexRoute: typeof AuthAdminIndexRoute
}

const AuthAdminRouteChildren: AuthAdminRouteChildren = {
  AuthAdminIndexRoute: AuthAdminIndexRoute,
}

const AuthAdminRouteWithChildren = AuthAdminRoute._addFileChildren(
  AuthAdminRouteChildren,
)

interface AuthUserRouteChildren {
  AuthUserHomeRoute: typeof AuthUserHomeRoute
  AuthUserIndexRoute: typeof AuthUserIndexRoute
}

const AuthUserRouteChildren: AuthUserRouteChildren = {
  AuthUserHomeRoute: AuthUserHomeRoute,
  AuthUserIndexRoute: AuthUserIndexRoute,
}

const AuthUserRouteWithChildren = AuthUserRoute._addFileChildren(
  AuthUserRouteChildren,
)

interface AuthRouteChildren {
  AuthAdminRoute: typeof AuthAdminRouteWithChildren
  AuthUserRoute: typeof AuthUserRouteWithChildren
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAdminRoute: AuthAdminRouteWithChildren,
  AuthUserRoute: AuthUserRouteWithChildren,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  UnauthLoginRoute: UnauthLoginRoute,
  UnauthSignupRoute: UnauthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
